/**
 * 心宠物品数据库
 * 包含80+贴合大学生生活的真实物品
 */

// 稀有度定义
const RARITY = {
  COMMON: { key: 'COMMON', label: '普通', color: '#9CA3AF', probability: 0.5 },
  UNCOMMON: { key: 'UNCOMMON', label: '少见', color: '#3B82F6', probability: 0.3 },
  RARE: { key: 'RARE', label: '稀有', color: '#8B5CF6', probability: 0.15 },
  EPIC: { key: 'EPIC', label: '史诗', color: '#F59E0B', probability: 0.04 },
  LEGENDARY: { key: 'LEGENDARY', label: '传说', color: '#EF4444', probability: 0.01 },
};

// 物品类型
const ITEM_TYPE = {
  STATIONERY: { key: 'STATIONERY', label: '文具' },
  TEXTBOOK: { key: 'TEXTBOOK', label: '教材' },
  ELECTRONIC: { key: 'ELECTRONIC', label: '电子' },
  FOOD: { key: 'FOOD', label: '食物' },
  DAILY: { key: 'DAILY', label: '日用' },
  DORM: { key: 'DORM', label: '宿舍' },
  SOCIAL: { key: 'SOCIAL', label: '社交' },
  SPORTS: { key: 'SPORTS', label: '运动' },
  SPECIAL: { key: 'SPECIAL', label: '特殊' },
};

// 物品数据库
const ITEM_DATABASE = [
  // ======== 文具类 (16个) ========
  {
    itemId: 'pen_001', name: '铅笔', type: 'STATIONERY', subType: '笔',
    icon: '✏️', rarity: 'COMMON',
    description: '普普通通的HB铅笔，笔杆上还有牙印——别问，问就是考试紧张咬的。',
    shortDesc: '普通的HB铅笔',
    price: 1, sellPrice: 0,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'TEACHER', name: '老师发放', probability: 0.3, scene: 'classroom' },
      { type: 'EXPLORE', name: '图书馆捡漏', probability: 0.2, scene: 'library' },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 5, desc: '学习加成5分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 99,
  },
  {
    itemId: 'pen_002', name: '中性笔', type: 'STATIONERY', subType: '笔',
    icon: '🖊️', rarity: 'COMMON',
    description: '0.5mm黑色中性笔，摔一下就不出墨的那种。建议多囤几根，毕竟考试周丢笔速度比掉头发还快。',
    shortDesc: '0.5mm黑色中性笔',
    price: 3, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'VENDING', name: '自动售货机', probability: 0.5 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 10, desc: '学习加成10分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 99,
  },
  {
    itemId: 'pen_003', name: '红笔', type: 'STATIONERY', subType: '笔',
    icon: '🔴', rarity: 'COMMON',
    description: '批改错题专用的红笔。借出去就回不来的那种，建议写上名字。',
    shortDesc: '批改专用红笔',
    price: 2, sellPrice: 0,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'TEACHER', name: '老师发放', probability: 0.2, scene: 'classroom' },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    specialEffect: { type: 'CORRECT_BOOST', value: 3, duration: 10, desc: '批改作业加成' },
    useLimit: { scenes: ['classroom', 'library', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 99,
  },
  {
    itemId: 'pen_004', name: '荧光笔', type: 'STATIONERY', subType: '笔',
    icon: '🖍️', rarity: 'UNCOMMON',
    description: '五颜六色的荧光笔，划线一时爽，复习火葬场。最后发现整本书都是重点。',
    shortDesc: '划重点专用荧光笔',
    price: 4, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 15, desc: '学习加成15分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 50,
  },
  {
    itemId: 'pen_005', name: '马克笔', type: 'STATIONERY', subType: '笔',
    icon: '🎨', rarity: 'UNCOMMON',
    description: '双头马克笔，画海报做手账的神器。缺点是 ink 跑得比你期末复习还快。',
    shortDesc: '双头马克笔',
    price: 6, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'TEACHER', name: '美术课发放', probability: 0.3, scene: 'classroom' },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'CREATIVE_BOOST', value: 5, duration: 20, desc: '创作加成20分钟' },
    useLimit: { scenes: ['classroom', 'library', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 30,
  },
  {
    itemId: 'erase_001', name: '橡皮擦', type: 'STATIONERY', subType: '橡皮',
    icon: '🧼', rarity: 'COMMON',
    description: '4B美术橡皮，擦得干净但容易变黑。用到最后总是找不到，然后发现在笔袋里碎成了渣。',
    shortDesc: '4B美术橡皮',
    price: 1, sellPrice: 0,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'TEACHER', name: '老师发放', probability: 0.4, scene: 'classroom' },
      { type: 'EXPLORE', name: '教室捡漏', probability: 0.3, scene: 'classroom' },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 99,
  },
  {
    itemId: 'correct_001', name: '修正带', type: 'STATIONERY', subType: '修正',
    icon: '🩹', rarity: 'UNCOMMON',
    description: '涂改错误的修正带。用的时候总是卡壳，像极了我写论文的思路。',
    shortDesc: '涂改修正带',
    price: 4, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 1, energy: 2, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 50,
  },
  {
    itemId: 'note_001', name: '便利贴', type: 'STATIONERY', subType: '便签',
    icon: '📝', rarity: 'COMMON',
    description: '彩色便利贴，写满了待办事项然后一个都没完成。最后全部贴在显示器边框上当装饰。',
    shortDesc: '彩色便利贴',
    price: 3, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'EXPLORE', name: '图书馆捡漏', probability: 0.3, scene: 'library' },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'TODO_BOOST', value: 3, duration: 30, desc: '待办效率+30%' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 50,
  },
  {
    itemId: 'clip_001', name: '回形针', type: 'STATIONERY', subType: '装订',
    icon: '📎', rarity: 'COMMON',
    description: '一盒回形针，用来夹资料。也可以掰直了当取卡针，大学生的万能工具。',
    shortDesc: '万能回形针',
    price: 1, sellPrice: 0,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'EXPLORE', name: '打印店捡漏', probability: 0.2, scene: 'town' },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 99,
  },
  {
    itemId: 'stapler_001', name: '订书机', type: 'STATIONERY', subType: '装订',
    icon: '📌', rarity: 'UNCOMMON',
    description: '迷你订书机，交作业前救急用。每次要订的时候才发现没钉子了。',
    shortDesc: '迷你订书机',
    price: 8, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'EXPLORE', name: '打印店捡漏', probability: 0.2, scene: 'town' },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'ORGANIZE_BOOST', value: 5, duration: 10, desc: '整理加成10分钟' },
    useLimit: { scenes: ['classroom', 'library', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'glue_001', name: '胶水', type: 'STATIONERY', subType: '粘合',
    icon: '🧴', rarity: 'COMMON',
    description: '普通白乳胶，做手工用。瓶盖永远拧不紧，干了之后就废了。',
    shortDesc: '白乳胶',
    price: 2, sellPrice: 0,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    useLimit: { scenes: ['classroom', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'scissor_001', name: '剪刀', type: 'STATIONERY', subType: '裁剪',
    icon: '✂️', rarity: 'COMMON',
    description: '普通剪刀，拆快递的神器。但高铁安检会被没收，记得别带回家。',
    shortDesc: '拆快递专用剪刀',
    price: 3, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'TEACHER', name: '手工课发放', probability: 0.2, scene: 'classroom' },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    useLimit: { scenes: ['classroom', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'ruler_001', name: '尺子套装', type: 'STATIONERY', subType: '测量',
    icon: '📏', rarity: 'COMMON',
    description: '20cm直尺+三角板+量角器三件套。画图作业必备，但丢了就再也凑不齐了。',
    shortDesc: '直尺三角板量角器套装',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 3, duration: 5, desc: '学习加成5分钟' },
    useLimit: { scenes: ['classroom', 'library', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'compass_001', name: '圆规', type: 'STATIONERY', subType: '测量',
    icon: '⭕', rarity: 'UNCOMMON',
    description: '金属圆规，数学课画圆用。针尖总是扎破笔袋，别问我怎么知道的。',
    shortDesc: '金属圆规',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'TEACHER', name: '数学课发放', probability: 0.3, scene: 'classroom' },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 10, desc: '学习加成10分钟' },
    useLimit: { scenes: ['classroom', 'library'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'calc_001', name: '计算器', type: 'STATIONERY', subType: '计算',
    icon: '🧮', rarity: 'RARE',
    description: '科学计算器，高数大物考试救命神器。考试时忘带它，等于没带脑子。',
    shortDesc: '科学计算器',
    price: 25, sellPrice: 10,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 8, duration: 20, desc: '学习加成20分钟' },
    useLimit: { scenes: ['classroom', 'library', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'usb_001', name: 'U盘', type: 'STATIONERY', subType: '存储',
    icon: '💾', rarity: 'RARE',
    description: '32GB金属外壳U盘，拷课件交作业全靠它。借出去三次，回来被格式化了两次。',
    shortDesc: '32GB U盘',
    price: 30, sellPrice: 12,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '数码店', probability: 0.8 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 30, desc: '存资料加成30分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },

  // ======== 教材类 (14个) ========
  {
    itemId: 'book_001', name: '语文书', type: 'TEXTBOOK', subType: '教材',
    icon: '📖', rarity: 'COMMON',
    description: '大学语文必修教材，里面夹着你上课偷偷画的涂鸦和暗恋对象的名字缩写。',
    shortDesc: '大学语文教材',
    price: 0, sellPrice: 5,
    sources: [
      { type: 'TEACHER', name: '老师发放', probability: 1, scene: 'classroom' },
    ],
    effect: { mood: 5, energy: 5, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 20, desc: '学习加成20分钟' },
    useLimit: { scenes: ['classroom', 'library'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'book_002', name: '数学书', type: 'TEXTBOOK', subType: '教材',
    icon: '📐', rarity: 'COMMON',
    description: '高等数学教材，厚度堪比砖头。每一页都写满了「不会」，最后一章还是白的。',
    shortDesc: '高等数学教材',
    price: 0, sellPrice: 5,
    sources: [
      { type: 'TEACHER', name: '老师发放', probability: 1, scene: 'classroom' },
    ],
    effect: { mood: 3, energy: 8, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 8, duration: 20, desc: '学习加成20分钟' },
    useLimit: { scenes: ['classroom', 'library'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'book_003', name: '英语书', type: 'TEXTBOOK', subType: '教材',
    icon: '🔤', rarity: 'COMMON',
    description: '大学英语综合教程，扉页写着「这学期一定好好学英语」——上学期也是这么写的。',
    shortDesc: '大学英语教材',
    price: 0, sellPrice: 5,
    sources: [
      { type: 'TEACHER', name: '老师发放', probability: 1, scene: 'classroom' },
    ],
    effect: { mood: 5, energy: 5, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 20, desc: '学习加成20分钟' },
    useLimit: { scenes: ['classroom', 'library'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'book_004', name: '专业课教材', type: 'TEXTBOOK', subType: '教材',
    icon: '📚', rarity: 'UNCOMMON',
    description: '专业核心课教材，定价298元。学长二手卖你30，你毕业了再卖下一届15，知识就是财富。',
    shortDesc: '专业核心课教材',
    price: 80, sellPrice: 30,
    sources: [
      { type: 'SHOP', name: '校园书店', probability: 1 },
      { type: 'EXPLORE', name: '二手群', probability: 0.6, scene: 'town' },
    ],
    effect: { mood: 5, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 10, duration: 30, desc: '学习加成30分钟' },
    useLimit: { scenes: ['classroom', 'library'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'book_005', name: '练习册', type: 'TEXTBOOK', subType: '练习',
    icon: '📋', rarity: 'COMMON',
    description: '课后习题集，老师说「选做」，但考试全从里面出。',
    shortDesc: '课后练习册',
    price: 10, sellPrice: 3,
    sources: [
      { type: 'TEACHER', name: '老师发放', probability: 0.5, scene: 'classroom' },
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 0, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 15, desc: '学习加成15分钟' },
    useLimit: { scenes: ['classroom', 'library'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'book_006', name: '考研资料', type: 'TEXTBOOK', subType: '考研',
    icon: '📑', rarity: 'RARE',
    description: '考研政治+英语+数学全套资料，共30斤。买了等于看了，看了等于会了。',
    shortDesc: '考研全套资料',
    price: 50, sellPrice: 20,
    sources: [
      { type: 'SHOP', name: '校园书店', probability: 1 },
      { type: 'EXPLORE', name: '二手群', probability: 0.7, scene: 'town' },
    ],
    effect: { mood: 8, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 15, duration: 45, desc: '学习加成45分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'book_007', name: '四六级真题', type: 'TEXTBOOK', subType: '考试',
    icon: '📄', rarity: 'UNCOMMON',
    description: '近十年真题+答案解析。每次考前一周翻出来做两套，然后继续裸考。',
    shortDesc: '四六级真题集',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '校园书店', probability: 1 },
      { type: 'EXPLORE', name: '二手群', probability: 0.5, scene: 'town' },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 8, duration: 20, desc: '学习加成20分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'book_008', name: '打印资料', type: 'TEXTBOOK', subType: '打印',
    icon: '🖨️', rarity: 'COMMON',
    description: '在打印店打的复习资料，纸张还温热着。一页5毛，期末周打印店排队比食堂还长。',
    shortDesc: '打印店复习资料',
    price: 5, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '打印店', probability: 1 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 10, desc: '学习加成10分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'book_009', name: '课程PPT打印版', type: 'TEXTBOOK', subType: '打印',
    icon: '📃', rarity: 'COMMON',
    description: '把老师PPT打印出来，一页6张那种。上课不用带电脑，但字小到要用放大镜。',
    shortDesc: 'PPT打印版',
    price: 5, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '打印店', probability: 1 },
      { type: 'SOCIAL', name: '同学分享', probability: 0.4 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 10, desc: '学习加成10分钟' },
    useLimit: { scenes: ['classroom', 'library'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'book_010', name: '实验报告本', type: 'TEXTBOOK', subType: '实验',
    icon: '🔬', rarity: 'COMMON',
    description: '实验课专用报告本，数据都是编的，但格式一定要对。',
    shortDesc: '实验报告本',
    price: 5, sellPrice: 1,
    sources: [
      { type: 'TEACHER', name: '老师发放', probability: 0.6, scene: 'classroom' },
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 15, desc: '实验加成15分钟' },
    useLimit: { scenes: ['classroom', 'laboratory'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'note_002', name: '薄笔记本', type: 'TEXTBOOK', subType: '笔记本',
    icon: '📓', rarity: 'COMMON',
    description: '40页薄笔记本，记一科笔记刚好用完。封面写着「高等数学」，里面画的都是火柴人打架。',
    shortDesc: '40页笔记本',
    price: 3, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'TEACHER', name: '老师发放', probability: 0.3, scene: 'classroom' },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 10, desc: '学习加成10分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'note_003', name: '厚笔记本', type: 'TEXTBOOK', subType: '笔记本',
    icon: '📔', rarity: 'COMMON',
    description: '100页厚笔记本，立志要用一学期。结果用了两周就换新的了，因为找不到记到哪了。',
    shortDesc: '100页厚笔记本',
    price: 8, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 20, desc: '学习加成20分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'note_004', name: '活页本', type: 'TEXTBOOK', subType: '笔记本',
    icon: '📒', rarity: 'UNCOMMON',
    description: '线圈活页本，可以随意增减页数。纸用完了买替芯，外壳用到毕业。',
    shortDesc: '线圈活页本',
    price: 10, sellPrice: 4,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 15, desc: '学习加成15分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'note_005', name: '错题本', type: 'TEXTBOOK', subType: '笔记本',
    icon: '❌', rarity: 'COMMON',
    description: '专门记录错题的本子。写了三页就放弃了，因为错的太多写不完。',
    shortDesc: '错题整理本',
    price: 6, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 8, duration: 20, desc: '错题复习加成20分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
];

module.exports = {
  RARITY,
  ITEM_TYPE,
  ITEM_DATABASE,
};

// 继续追加剩余物品数据
const ITEM_DATABASE_PART2 = [
  // ======== 电子设备/配件 (12个) ========
  {
    itemId: 'power_001', name: '充电宝', type: 'ELECTRONIC', subType: '电源',
    icon: '🔋', rarity: 'RARE',
    description: '20000mAh充电宝，宿舍断电后的续命神器。但永远不知道它还有没有电，因为指示灯坏了。',
    shortDesc: '20000mAh充电宝',
    price: 60, sellPrice: 25,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '数码店', probability: 0.9 },
    ],
    effect: { mood: 0, energy: 20, social: 0 },
    specialEffect: { type: 'ENERGY_BOOST', value: 20, duration: 0, desc: '立即恢复20点能量' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'cable_001', name: '数据线', type: 'ELECTRONIC', subType: '线材',
    icon: '🔌', rarity: 'UNCOMMON',
    description: 'Type-C快充线，3个月必坏定律。宿舍里永远有人在借数据线，永远有人找不到自己的。',
    shortDesc: 'Type-C快充线',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '数码店', probability: 0.8 },
      { type: 'SOCIAL', name: '室友赠送', probability: 0.3 },
    ],
    effect: { mood: 3, energy: 0, social: 2 },
    useLimit: { scenes: ['classroom', 'library', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'earphone_001', name: '蓝牙耳机', type: 'ELECTRONIC', subType: '耳机',
    icon: '🎧', rarity: 'EPIC',
    description: '降噪蓝牙耳机，图书馆沉浸式学习必备。戴上它，全世界都安静了——除了你自己的心跳声。',
    shortDesc: '降噪蓝牙耳机',
    price: 120, sellPrice: 50,
    sources: [
      { type: 'SHOP', name: '数码店', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 8, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 10, duration: 20, desc: '沉浸式学习20分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 2,
  },
  {
    itemId: 'earphone_002', name: '有线耳机', type: 'ELECTRONIC', subType: '耳机',
    icon: '🎧', rarity: 'UNCOMMON',
    description: '带麦有线耳机，线永远会缠成麻花。优点是永远不会没电，缺点是线永远会断。',
    shortDesc: '带麦有线耳机',
    price: 30, sellPrice: 10,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '数码店', probability: 0.7 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 10, desc: '学习加成10分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'stand_001', name: '手机支架', type: 'ELECTRONIC', subType: '支架',
    icon: '📱', rarity: 'COMMON',
    description: '折叠手机支架，吃饭追剧必备。但每次都是拿外卖盒或水杯代替，买来就吃灰。',
    shortDesc: '折叠手机支架',
    price: 10, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.8 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    useLimit: { scenes: ['classroom', 'dormitory', 'bedroom', 'cafeteria'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'mouse_001', name: '鼠标', type: 'ELECTRONIC', subType: '外设',
    icon: '🖱️', rarity: 'UNCOMMON',
    description: '静音无线鼠标，图书馆不打扰他人。但接收器比鼠标还容易丢。',
    shortDesc: '静音无线鼠标',
    price: 40, sellPrice: 15,
    sources: [
      { type: 'SHOP', name: '数码店', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 10, desc: '学习加成10分钟' },
    useLimit: { scenes: ['library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'pad_001', name: '鼠标垫', type: 'ELECTRONIC', subType: '外设',
    icon: '🟫', rarity: 'COMMON',
    description: '大号鼠标垫，印有世界地图或动漫图案。用久了边缘会翘起来。',
    shortDesc: '大号鼠标垫',
    price: 8, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.7 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    useLimit: { scenes: ['library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'cover_001', name: '键盘膜', type: 'ELECTRONIC', subType: '外设',
    icon: '⌨️', rarity: 'COMMON',
    description: '透明键盘保护膜，防止零食渣掉进键盘。但你真的会在电脑前吃东西吗？会。',
    shortDesc: '键盘保护膜',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'hdd_001', name: '移动硬盘', type: 'ELECTRONIC', subType: '存储',
    icon: '💿', rarity: 'RARE',
    description: '1TB移动硬盘，装着大学四年所有回忆。包括但不限于：课件、论文、游戏、电影、以及那些再也不敢打开的照片。',
    shortDesc: '1TB移动硬盘',
    price: 80, sellPrice: 35,
    sources: [
      { type: 'SHOP', name: '数码店', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 5, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 30, desc: '存资料加成30分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 2,
  },
  {
    itemId: 'stand_002', name: '平板支架', type: 'ELECTRONIC', subType: '支架',
    icon: '📲', rarity: 'UNCOMMON',
    description: 'iPad专用支架，看网课解放双手。但更多时候是用来放泡面盖。',
    shortDesc: '平板支架',
    price: 20, sellPrice: 8,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 10, desc: '看网课加成10分钟' },
    useLimit: { scenes: ['library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'socket_001', name: '插线板', type: 'ELECTRONIC', subType: '电源',
    icon: '🔌', rarity: 'UNCOMMON',
    description: '6孔插线板+USB口，宿舍床位唯一电源的救命稻草。上面插满了充电器、台灯、风扇、充电宝，功率永远逼近跳闸边缘。',
    shortDesc: '6孔插线板',
    price: 25, sellPrice: 10,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.8 },
    ],
    effect: { mood: 2, energy: 5, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'fan_001', name: '小风扇', type: 'ELECTRONIC', subType: '风扇',
    icon: '🌀', rarity: 'UNCOMMON',
    description: 'USB小风扇，夏天宿舍没空调时的唯一慰藉。噪音大得像拖拉机，但你还是会开着它睡觉。',
    shortDesc: 'USB小风扇',
    price: 20, sellPrice: 8,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.8 },
    ],
    effect: { mood: 5, energy: 5, social: 0 },
    specialEffect: { type: 'SEASON_BOOST', value: 10, duration: 30, desc: '夏天使用效果翻倍' },
    useLimit: { scenes: ['classroom', 'dormitory', 'bedroom', 'library'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },

  // ======== 食品饮料类 (18个) ========
  {
    itemId: 'drink_001', name: '矿泉水', type: 'FOOD', subType: '饮料',
    icon: '💧', rarity: 'COMMON',
    description: '550ml纯净水，体育课后的救命水。瓶子不要扔，可以当哑铃。',
    shortDesc: '550ml纯净水',
    price: 2, sellPrice: 0,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'VENDING', name: '自动售货机', probability: 0.9 },
    ],
    effect: { mood: 0, energy: 8, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom', 'playground', 'cafeteria'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'drink_002', name: '可乐', type: 'FOOD', subType: '饮料',
    icon: '🥤', rarity: 'COMMON',
    description: '冰可乐，快乐水。第一口值三块五，后面的都是送的。但别在上课前喝，否则会在老师讲到重点时疯狂打嗝。',
    shortDesc: '冰可乐',
    price: 4, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'CAFETERIA', name: '食堂小卖部', probability: 0.8 },
    ],
    effect: { mood: 5, energy: 5, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom', 'cafeteria'], minMood: 0, minEnergy: 0 },
    maxStack: 12,
  },
  {
    itemId: 'drink_003', name: '雪碧', type: 'FOOD', subType: '饮料',
    icon: '🍋', rarity: 'COMMON',
    description: '清爽雪碧，比可乐少点罪恶感。其实糖分一样高，只是绿色的看起来健康。',
    shortDesc: '清爽雪碧',
    price: 4, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'CAFETERIA', name: '食堂小卖部', probability: 0.8 },
    ],
    effect: { mood: 4, energy: 5, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom', 'cafeteria'], minMood: 0, minEnergy: 0 },
    maxStack: 12,
  },
  {
    itemId: 'drink_004', name: '奶茶', type: 'FOOD', subType: '饮料',
    icon: '🧋', rarity: 'UNCOMMON',
    description: '珍珠奶茶，全糖去冰。下午没课的时候，和室友一起拼单点奶茶，是大学生活最幸福的时刻之一。',
    shortDesc: '珍珠奶茶',
    price: 12, sellPrice: 4,
    sources: [
      { type: 'CAFETERIA', name: '食堂奶茶店', probability: 0.9 },
      { type: 'SHOP', name: '校外奶茶店', probability: 1 },
    ],
    effect: { mood: 10, energy: 8, social: 3 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom', 'cafeteria'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'drink_005', name: '咖啡', type: 'FOOD', subType: '饮料',
    icon: '☕', rarity: 'UNCOMMON',
    description: '速溶黑咖啡，期末周续命神器。凌晨两点的图书馆，空气中都是咖啡味。喝久了你会发现，苦的其实不是咖啡，是你的生活。',
    shortDesc: '速溶黑咖啡',
    price: 8, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '咖啡店', probability: 0.9 },
    ],
    effect: { mood: 5, energy: 20, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 10, duration: 15, desc: '熬夜学习加成15分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'drink_006', name: '茶叶', type: 'FOOD', subType: '饮料',
    icon: '🍵', rarity: 'UNCOMMON',
    description: '绿茶茶叶，养生大学生必备。保温杯里泡枸杞是下一阶段，现在还只是泡茶叶。',
    shortDesc: '绿茶茶叶',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 5, energy: 10, social: 0 },
    useLimit: { scenes: ['library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'food_001', name: '泡面', type: 'FOOD', subType: '速食',
    icon: '🍜', rarity: 'COMMON',
    description: '红烧牛肉面，宿舍夜宵之王。热水壶一响，全宿舍都醒了。但别说，那香味真的馋人。',
    shortDesc: '红烧牛肉面',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'EXPLORE', name: '宿舍囤货', probability: 0.5, scene: 'bedroom' },
    ],
    effect: { mood: 3, energy: 15, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'food_002', name: '自热火锅', type: 'FOOD', subType: '速食',
    icon: '🍲', rarity: 'UNCOMMON',
    description: '自热小火锅，宿舍聚餐的豪华版。虽然肉只有两片，但仪式感拉满。注意别触发烟雾报警器。',
    shortDesc: '自热小火锅',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.8 },
    ],
    effect: { mood: 8, energy: 20, social: 2 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'food_003', name: '面包', type: 'FOOD', subType: '烘焙',
    icon: '🍞', rarity: 'COMMON',
    description: '全麦吐司面包，早八课救命粮。口袋里揣两片，路上边走边吃，是大学生最狼狈也最真实的模样。',
    shortDesc: '全麦吐司面包',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'CAFETERIA', name: '食堂面包房', probability: 0.8 },
      { type: 'VENDING', name: '自动售货机', probability: 0.6 },
    ],
    effect: { mood: 3, energy: 12, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 15,
  },
  {
    itemId: 'food_004', name: '饼干', type: 'FOOD', subType: '零食',
    icon: '🍪', rarity: 'COMMON',
    description: '夹心饼干，课间充饥小零食。上课偷吃的时候声音太大，建议提前掰成小块。',
    shortDesc: '夹心饼干',
    price: 6, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 5, energy: 5, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 15,
  },
  {
    itemId: 'food_005', name: '巧克力', type: 'FOOD', subType: '零食',
    icon: '🍫', rarity: 'COMMON',
    description: '黑巧克力，心情不好的时候来一块。虽然会变胖，但快乐是无价的。',
    shortDesc: '黑巧克力',
    price: 8, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'VENDING', name: '自动售货机', probability: 0.7 },
    ],
    effect: { mood: 10, energy: 5, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 15,
  },
  {
    itemId: 'food_006', name: '薯片', type: 'FOOD', subType: '零食',
    icon: '🥔', rarity: 'COMMON',
    description: '原味薯片，咔嚓咔嚓的声音很治愈。但别在图书馆吃，会被周围人瞪。',
    shortDesc: '原味薯片',
    price: 6, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 8, energy: 3, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom', 'cafeteria'], minMood: 0, minEnergy: 0 },
    maxStack: 12,
  },
  {
    itemId: 'food_007', name: '辣条', type: 'FOOD', subType: '零食',
    icon: '🌶️', rarity: 'COMMON',
    description: '卫龙大面筋，宿舍社交硬通货。一根辣条能换来室友的作业答案，这就是它的价值。',
    shortDesc: '卫龙大面筋',
    price: 3, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'CAFETERIA', name: '食堂小卖部', probability: 0.9 },
    ],
    effect: { mood: 8, energy: 2, social: 2 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 30,
  },
  {
    itemId: 'food_008', name: '水果', type: 'FOOD', subType: '水果',
    icon: '🍎', rarity: 'COMMON',
    description: '新鲜苹果，每天一苹果，医生远离我。虽然你也不是每天都吃。',
    shortDesc: '新鲜苹果',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'CAFETERIA', name: '食堂水果店', probability: 0.8 },
    ],
    effect: { mood: 5, energy: 8, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 15,
  },
  {
    itemId: 'food_009', name: '牛奶', type: 'FOOD', subType: '饮料',
    icon: '🥛', rarity: 'COMMON',
    description: '纯牛奶，睡前喝一杯。虽然更多时候是用来冲咖啡的。',
    shortDesc: '纯牛奶',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'VENDING', name: '自动售货机', probability: 0.8 },
    ],
    effect: { mood: 3, energy: 10, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 15,
  },
  {
    itemId: 'drink_007', name: '能量饮料', type: 'FOOD', subType: '饮料',
    icon: '⚡', rarity: 'UNCOMMON',
    description: '红牛功能饮料，通宵赶DDL的神器。但别连喝三罐，心脏会抗议。',
    shortDesc: '功能饮料',
    price: 8, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'VENDING', name: '自动售货机', probability: 0.8 },
    ],
    effect: { mood: 3, energy: 25, social: 0 },
    specialEffect: { type: 'ENERGY_BOOST', value: 25, duration: 0, desc: '立即恢复25点能量' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 12,
  },
  {
    itemId: 'food_010', name: '冰淇淋', type: 'FOOD', subType: '冷饮',
    icon: '🍦', rarity: 'UNCOMMON',
    description: '甜筒冰淇淋，夏天操场边的小确幸。但化得比你恋爱还快，得赶紧舔。',
    shortDesc: '甜筒冰淇淋',
    price: 6, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'CAFETERIA', name: '食堂冷饮店', probability: 0.8 },
    ],
    effect: { mood: 12, energy: 3, social: 0 },
    specialEffect: { type: 'SEASON_BOOST', value: 5, duration: 0, desc: '夏天使用额外心情+5' },
    useLimit: { scenes: ['classroom', 'playground', 'cafeteria', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'food_011', name: '棒棒糖', type: 'FOOD', subType: '糖果',
    icon: '🍭', rarity: 'COMMON',
    description: '水果味棒棒糖，便宜又好吃。心情低落的时候来一根，假装自己还是小学生。',
    shortDesc: '水果味棒棒糖',
    price: 2, sellPrice: 0,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'CAFETERIA', name: '食堂小卖部', probability: 0.9 },
    ],
    effect: { mood: 5, energy: 0, social: 2 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 30,
  },
];

// 合并数据
ITEM_DATABASE.push(...ITEM_DATABASE_PART2);

module.exports = {
  RARITY,
  ITEM_TYPE,
  ITEM_DATABASE,
};

// 继续追加剩余物品数据
const ITEM_DATABASE_PART3 = [
  // ======== 生活日用品 (12个) ========
  {
    itemId: 'paper_001', name: '纸巾', type: 'DAILY', subType: '纸品',
    icon: '🧻', rarity: 'COMMON',
    description: '三层抽纸，大学生刚需。感冒时一周用一包，平时一包用一学期。',
    shortDesc: '三层抽纸',
    price: 3, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'VENDING', name: '自动售货机', probability: 0.8 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 30,
  },
  {
    itemId: 'wipe_001', name: '湿巾', type: 'DAILY', subType: '清洁',
    icon: '🧽', rarity: 'COMMON',
    description: '酒精湿巾，擦桌子擦手机擦一切。疫情期间养成的习惯，现在改不掉了。',
    shortDesc: '酒精湿巾',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'mask_001', name: '口罩', type: 'DAILY', subType: '防护',
    icon: '😷', rarity: 'COMMON',
    description: '一次性医用口罩，出门必备。虽然现在不强制了，但习惯还在。而且没化妆的时候真的很需要。',
    shortDesc: '医用口罩',
    price: 8, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '药店', probability: 0.9 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    specialEffect: { type: 'HEALTH_BOOST', value: 1, duration: 0, desc: '健康+1' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom', 'playground'], minMood: 0, minEnergy: 0 },
    maxStack: 50,
  },
  {
    itemId: 'umbrella_001', name: '雨伞', type: 'DAILY', subType: '雨具',
    icon: '☂️', rarity: 'UNCOMMON',
    description: '折叠雨伞，大学生最容易丢的物品TOP3。每个学期至少买两把，毕业时宿舍能凑出10把。',
    shortDesc: '折叠雨伞',
    price: 25, sellPrice: 10,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.8 },
    ],
    effect: { mood: 5, energy: 0, social: 0 },
    specialEffect: { type: 'WEATHER_BOOST', value: 10, duration: 0, desc: '雨天使用心情额外+10' },
    useLimit: { scenes: ['classroom', 'library', 'dormitory', 'bedroom', 'playground'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'bandage_001', name: '创可贴', type: 'DAILY', subType: '医疗',
    icon: '🩹', rarity: 'COMMON',
    description: '防水创可贴，磨脚神器。新鞋必磨脚，创可贴是鞋和脚之间的和平条约。',
    shortDesc: '防水创可贴',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '药店', probability: 0.9 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    specialEffect: { type: 'HEALTH_BOOST', value: 2, duration: 0, desc: '健康+2' },
    useLimit: { scenes: ['classroom', 'library', 'dormitory', 'bedroom', 'playground'], minMood: 0, minEnergy: 0 },
    maxStack: 30,
  },
  {
    itemId: 'eyedrop_001', name: '眼药水', type: 'DAILY', subType: '医疗',
    icon: '👁️', rarity: 'UNCOMMON',
    description: '缓解眼疲劳的眼药水，看了一天电脑后的救赎。但别滴太多，会有依赖性。',
    shortDesc: '缓解眼疲劳眼药水',
    price: 18, sellPrice: 7,
    sources: [
      { type: 'SHOP', name: '药店', probability: 1 },
      { type: 'SHOP', name: '校园超市', probability: 0.7 },
    ],
    effect: { mood: 3, energy: 3, social: 0 },
    useLimit: { scenes: ['library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'balm_001', name: '风油精', type: 'DAILY', subType: '医疗',
    icon: '🌿', rarity: 'COMMON',
    description: '风油精，提神醒脑驱蚊止痒万能油。涂太阳穴上能清醒，涂蚊子包上能止痒，涂同学椅子上能绝交。',
    shortDesc: '万能风油精',
    price: 8, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '药店', probability: 1 },
      { type: 'SHOP', name: '校园超市', probability: 0.8 },
    ],
    effect: { mood: 3, energy: 5, social: 0 },
    specialEffect: { type: 'ENERGY_BOOST', value: 5, duration: 0, desc: '提神醒脑' },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 15,
  },
  {
    itemId: 'bottle_001', name: '保温杯', type: 'DAILY', subType: '杯具',
    icon: '🍶', rarity: 'UNCOMMON',
    description: '500ml保温杯，养生大学生标配。里面泡着枸杞、菊花、或者昨天的奶茶。',
    shortDesc: '500ml保温杯',
    price: 30, sellPrice: 12,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 3, energy: 3, social: 0 },
    useLimit: { scenes: ['classroom', 'library', 'study_room', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'lunchbox_001', name: '饭盒', type: 'DAILY', subType: '餐具',
    icon: '🥡', rarity: 'COMMON',
    description: '塑料饭盒，食堂打包专用。但更多时候还是直接用塑料袋，因为懒得洗。',
    shortDesc: '塑料饭盒',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    useLimit: { scenes: ['cafeteria', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'detergent_001', name: '洗衣液', type: 'DAILY', subType: '清洁',
    icon: '🧴', rarity: 'COMMON',
    description: '薰衣草香洗衣液，一周洗一次衣服的仪式感。但往往是衣服堆成山了才洗。',
    shortDesc: '薰衣草洗衣液',
    price: 20, sellPrice: 8,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'shampoo_001', name: '洗发水小样', type: 'DAILY', subType: '洗护',
    icon: '🧴', rarity: 'COMMON',
    description: '酒店薅来的洗发水小样，旅行装大小。虽然是免费的，但用着还行。',
    shortDesc: '旅行装洗发水',
    price: 0, sellPrice: 0,
    sources: [
      { type: 'SOCIAL', name: '酒店薅的', probability: 0.5 },
      { type: 'SOCIAL', name: '室友赠送', probability: 0.3 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'clipper_001', name: '指甲刀', type: 'DAILY', subType: '工具',
    icon: '💅', rarity: 'COMMON',
    description: '迷你指甲刀，宿舍必备。但永远找不到，需要剪指甲的时候永远在别人的抽屉里。',
    shortDesc: '迷你指甲刀',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },

  // ======== 宿舍用品 (10个) ========
  {
    itemId: 'curtain_001', name: '床帘', type: 'DORM', subType: '床品',
    icon: '🛏️', rarity: 'UNCOMMON',
    description: '遮光床帘，宿舍最后的隐私防线。拉上它，就是你的独立王国。缺点是夏天会很闷。',
    shortDesc: '遮光床帘',
    price: 40, sellPrice: 15,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
      { type: 'EXPLORE', name: '二手群', probability: 0.6, scene: 'town' },
    ],
    effect: { mood: 5, energy: 0, social: 0 },
    specialEffect: { type: 'PRIVACY_BOOST', value: 1, duration: 0, desc: '隐私+1' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 2,
  },
  {
    itemId: 'box_001', name: '收纳盒', type: 'DORM', subType: '收纳',
    icon: '📦', rarity: 'COMMON',
    description: '塑料收纳盒，把乱七八糟的东西装进去，眼不见为净。但打开来还是一团乱。',
    shortDesc: '塑料收纳盒',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'ORGANIZE_BOOST', value: 3, duration: 0, desc: '整理加成' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'hook_001', name: '挂钩', type: 'DORM', subType: '收纳',
    icon: '🪝', rarity: 'COMMON',
    description: '强力粘钩，挂书包挂衣服挂一切。但总是会掉，然后半夜掉下来吓你一跳。',
    shortDesc: '强力粘钩',
    price: 5, sellPrice: 1,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.8 },
    ],
    effect: { mood: 1, energy: 0, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 30,
  },
  {
    itemId: 'lamp_001', name: '小台灯', type: 'DORM', subType: '照明',
    icon: '💡', rarity: 'UNCOMMON',
    description: 'LED充电台灯，熄灯后的续命光源。三档亮度，最亮那档能用半小时，最暗那档能撑到通宵。',
    shortDesc: 'LED充电台灯',
    price: 25, sellPrice: 10,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 5, duration: 10, desc: '夜间学习加成10分钟' },
    useLimit: { scenes: ['dormitory', 'bedroom', 'library'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'pillow_001', name: '抱枕', type: 'DORM', subType: '床品',
    icon: '🧸', rarity: 'UNCOMMON',
    description: '大号毛绒抱枕，抱着睡觉超有安全感。也是你在这个城市唯一的「家人」。',
    shortDesc: '大号毛绒抱枕',
    price: 20, sellPrice: 8,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
      { type: 'SOCIAL', name: '朋友赠送', probability: 0.4 },
    ],
    effect: { mood: 8, energy: 5, social: 0 },
    specialEffect: { type: 'SLEEP_BOOST', value: 5, duration: 0, desc: '睡眠质量+5' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'rug_001', name: '地毯', type: 'DORM', subType: '装饰',
    icon: '🟫', rarity: 'UNCOMMON',
    description: '小地毯，铺在床边，下床不用踩冰冷的地板。但打扫起来很烦，最后变成了猫砂盆。',
    shortDesc: '床边小地毯',
    price: 35, sellPrice: 12,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
    ],
    effect: { mood: 5, energy: 0, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 2,
  },
  {
    itemId: 'poster_001', name: '海报', type: 'DORM', subType: '装饰',
    icon: '🖼️', rarity: 'COMMON',
    description: '偶像/动漫/风景海报，贴在墙上装饰。毕业时撕下来，墙上留下了一个个印子。',
    shortDesc: '墙贴海报',
    price: 10, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
      { type: 'SOCIAL', name: '活动领取', probability: 0.5 },
    ],
    effect: { mood: 5, energy: 0, social: 0 },
    specialEffect: { type: 'DECOR_BOOST', value: 1, duration: 0, desc: '装饰值+1' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'plant_001', name: '绿植', type: 'DORM', subType: '植物',
    icon: '🪴', rarity: 'UNCOMMON',
    description: '多肉植物或绿萝，宿舍里的生命。你发誓会好好照顾它，但一个月后它变成了干尸。',
    shortDesc: '多肉/绿萝',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 5, energy: 0, social: 0 },
    specialEffect: { type: 'DAILY_MOOD', value: 1, duration: 0, desc: '每天自动心情+1' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'aroma_001', name: '香薰', type: 'DORM', subType: '香氛',
    icon: '🕯️', rarity: 'UNCOMMON',
    description: '无火香薰，让宿舍充满香味。但别买太浓的，否则室友会以为你在掩盖什么。',
    shortDesc: '无火香薰',
    price: 20, sellPrice: 8,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
      { type: 'SOCIAL', name: '朋友赠送', probability: 0.3 },
    ],
    effect: { mood: 8, energy: 3, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'alarm_001', name: '闹钟', type: 'DORM', subType: '计时',
    icon: '⏰', rarity: 'COMMON',
    description: '机械闹钟，声音大到能吵醒整层楼。但你自己永远听不见，全靠室友叫你。',
    shortDesc: '机械闹钟',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.8 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'ANTI_LATE', value: 5, duration: 0, desc: '防迟到' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
];

ITEM_DATABASE.push(...ITEM_DATABASE_PART3);

module.exports = {
  RARITY,
  ITEM_TYPE,
  ITEM_DATABASE,
};

// 继续追加最后几类物品
const ITEM_DATABASE_PART4 = [
  // ======== 社交/娱乐 (8个) ========
  {
    itemId: 'card_001', name: '扑克牌', type: 'SOCIAL', subType: '桌游',
    icon: '🃏', rarity: 'COMMON',
    description: '一副扑克牌，宿舍社交硬通货。斗地主、掼蛋、21点，一副牌能玩一整个学期。',
    shortDesc: '标准扑克牌',
    price: 5, sellPrice: 2,
    sources: [
      { type: 'SHOP', name: '校园超市', probability: 1 },
      { type: 'SOCIAL', name: '同学赠送', probability: 0.5 },
    ],
    effect: { mood: 5, energy: 0, social: 8 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 10 },
    maxStack: 5,
  },
  {
    itemId: 'boardgame_001', name: '桌游', type: 'SOCIAL', subType: '桌游',
    icon: '🎲', rarity: 'UNCOMMON',
    description: '狼人杀/剧本杀/UNO，宿舍聚会神器。一玩就是通宵，第二天集体迟到。',
    shortDesc: '狼人杀/UNO桌游',
    price: 30, sellPrice: 10,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
      { type: 'SOCIAL', name: '同学赠送', probability: 0.3 },
    ],
    effect: { mood: 8, energy: 0, social: 10 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 15 },
    maxStack: 3,
  },
  {
    itemId: 'ticket_001', name: '电影票', type: 'SOCIAL', subType: '票券',
    icon: '🎫', rarity: 'UNCOMMON',
    description: '电影票兑换券，和朋友一起看电影的快乐。虽然更多时候是在宿舍看盗版。',
    shortDesc: '电影票兑换券',
    price: 0, sellPrice: 15,
    sources: [
      { type: 'SOCIAL', name: '朋友赠送', probability: 0.5 },
      { type: 'SOCIAL', name: '活动获得', probability: 0.7 },
    ],
    effect: { mood: 10, energy: 0, social: 5 },
    useLimit: { scenes: ['dormitory', 'bedroom', 'town'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'coupon_001', name: '奶茶券', type: 'SOCIAL', subType: '票券',
    icon: '🧾', rarity: 'COMMON',
    description: '奶茶店优惠券，第二杯半价或买一送一。总是找不到人一起拼单。',
    shortDesc: '奶茶优惠券',
    price: 0, sellPrice: 3,
    sources: [
      { type: 'SOCIAL', name: '朋友赠送', probability: 0.4 },
      { type: 'SOCIAL', name: '活动获得', probability: 0.6 },
    ],
    effect: { mood: 5, energy: 0, social: 2 },
    useLimit: { scenes: ['cafeteria', 'town'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'coupon_002', name: '外卖券', type: 'SOCIAL', subType: '票券',
    icon: '🧾', rarity: 'COMMON',
    description: '外卖APP满减券，满25减5。为了凑满减硬是多点了一份米饭，结果吃不完。',
    shortDesc: '外卖满减券',
    price: 0, sellPrice: 2,
    sources: [
      { type: 'SOCIAL', name: 'APP领取', probability: 1 },
      { type: 'SOCIAL', name: '朋友分享', probability: 0.8 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'pick_001', name: '吉他拨片', type: 'SOCIAL', subType: '乐器',
    icon: '🎸', rarity: 'COMMON',
    description: '吉他拨片，音乐社活动送的。虽然你不会弹吉他，但放在桌上很有文艺气息。',
    shortDesc: '吉他拨片',
    price: 2, sellPrice: 0,
    sources: [
      { type: 'SOCIAL', name: '音乐社活动', probability: 0.6 },
      { type: 'SHOP', name: '网购', probability: 1 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'CREATIVE_BOOST', value: 3, duration: 5, desc: '创作加成5分钟' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'ball_001', name: '篮球', type: 'SOCIAL', subType: '球类',
    icon: '🏀', rarity: 'RARE',
    description: '斯伯丁篮球，球场上的社交货币。会打球的男生自带光环，但别在女生面前砸到脚。',
    shortDesc: '斯伯丁篮球',
    price: 80, sellPrice: 30,
    sources: [
      { type: 'SHOP', name: '体育用品店', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 10, energy: 10, social: 5 },
    specialEffect: { type: 'SPORTS_BOOST', value: 10, duration: 30, desc: '运动加成30分钟' },
    useLimit: { scenes: ['playground'], minMood: 0, minEnergy: 20 },
    maxStack: 2,
  },
  {
    itemId: 'racket_001', name: '羽毛球拍', type: 'SOCIAL', subType: '球类',
    icon: '🏸', rarity: 'RARE',
    description: '碳素羽毛球拍，轻便好打。和室友在宿舍楼下打，球永远会上树。',
    shortDesc: '碳素羽毛球拍',
    price: 60, sellPrice: 25,
    sources: [
      { type: 'SHOP', name: '体育用品店', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 8, energy: 8, social: 5 },
    specialEffect: { type: 'SPORTS_BOOST', value: 8, duration: 30, desc: '运动加成30分钟' },
    useLimit: { scenes: ['playground'], minMood: 0, minEnergy: 15 },
    maxStack: 2,
  },

  // ======== 运动健康 (8个) ========
  {
    itemId: 'band_001', name: '运动手环', type: 'SPORTS', subType: '穿戴',
    icon: '⌚', rarity: 'EPIC',
    description: '智能运动手环，记录步数心率睡眠。主要用来当手表看时间，和闹钟震醒自己。',
    shortDesc: '智能运动手环',
    price: 150, sellPrice: 60,
    sources: [
      { type: 'SHOP', name: '数码店', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 5, energy: 5, social: 0 },
    specialEffect: { type: 'HEALTH_TRACK', value: 5, duration: 0, desc: '健康监测+5' },
    useLimit: { scenes: ['playground', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 1,
  },
  {
    itemId: 'yoga_001', name: '瑜伽垫', type: 'SPORTS', subType: '器材',
    icon: '🧘', rarity: 'UNCOMMON',
    description: 'TPE瑜伽垫，宿舍健身必备。铺开来能做瑜伽，卷起来能当枕头，脏了还能当地毯。',
    shortDesc: 'TPE瑜伽垫',
    price: 40, sellPrice: 15,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
      { type: 'SHOP', name: '体育用品店', probability: 0.8 },
    ],
    effect: { mood: 5, energy: 5, social: 0 },
    specialEffect: { type: 'SPORTS_BOOST', value: 5, duration: 20, desc: '瑜伽加成20分钟' },
    useLimit: { scenes: ['dormitory', 'bedroom', 'playground'], minMood: 0, minEnergy: 0 },
    maxStack: 2,
  },
  {
    itemId: 'rope_001', name: '跳绳', type: 'SPORTS', subType: '器材',
    icon: '🪢', rarity: 'COMMON',
    description: '计数跳绳，减肥利器。跳了三天就放弃了，因为腿太酸。但计数功能真的很酷。',
    shortDesc: '计数跳绳',
    price: 15, sellPrice: 5,
    sources: [
      { type: 'SHOP', name: '体育用品店', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 5, energy: 8, social: 0 },
    specialEffect: { type: 'SPORTS_BOOST', value: 8, duration: 15, desc: '跳绳加成15分钟' },
    useLimit: { scenes: ['playground', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 10 },
    maxStack: 3,
  },
  {
    itemId: 'protein_001', name: '蛋白粉', type: 'SPORTS', subType: '补剂',
    icon: '🥛', rarity: 'RARE',
    description: '乳清蛋白粉，健身党的信仰。一大桶能喝一学期，但更多的是放在柜子里当装饰。',
    shortDesc: '乳清蛋白粉',
    price: 80, sellPrice: 30,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
    ],
    effect: { mood: 3, energy: 10, social: 0 },
    specialEffect: { type: 'HEALTH_BOOST', value: 5, duration: 0, desc: '健康+5' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 3,
  },
  {
    itemId: 'vitamin_001', name: '维生素', type: 'SPORTS', subType: '补剂',
    icon: '💊', rarity: 'UNCOMMON',
    description: '复合维生素片，养生大学生必备。买了一瓶100片，吃了10片就忘了，过期了再扔。',
    shortDesc: '复合维生素',
    price: 30, sellPrice: 10,
    sources: [
      { type: 'SHOP', name: '药店', probability: 1 },
      { type: 'SHOP', name: '网购', probability: 0.9 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'HEALTH_BOOST', value: 5, duration: 0, desc: '健康+5' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'massage_001', name: '筋膜枪', type: 'SPORTS', subType: '按摩',
    icon: '🔫', rarity: 'EPIC',
    description: 'mini筋膜枪，运动后放松肌肉。但更多时候是用来按肩膀，因为久坐肩膀太酸了。',
    shortDesc: 'mini筋膜枪',
    price: 200, sellPrice: 80,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
    ],
    effect: { mood: 5, energy: 10, social: 0 },
    specialEffect: { type: 'RECOVERY_BOOST', value: 10, duration: 0, desc: '恢复+10' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 1,
  },
  {
    itemId: 'scale_001', name: '体重秤', type: 'SPORTS', subType: '测量',
    icon: '⚖️', rarity: 'UNCOMMON',
    description: '电子体重秤，每天早上空腹称重。数字涨了就是秤不准，数字跌了就是瘦了。',
    shortDesc: '电子体重秤',
    price: 40, sellPrice: 15,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
      { type: 'SHOP', name: '超市', probability: 0.7 },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    specialEffect: { type: 'HEALTH_TRACK', value: 3, duration: 0, desc: '健康监测+3' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 1,
  },
  {
    itemId: 'mask_002', name: '眼罩', type: 'SPORTS', subType: '睡眠',
    icon: '🥽', rarity: 'COMMON',
    description: '遮光眼罩，宿舍早睡必备。戴上它，室友的灯、手机的光、窗外的路灯都与你无关。',
    shortDesc: '遮光眼罩',
    price: 10, sellPrice: 3,
    sources: [
      { type: 'SHOP', name: '网购', probability: 1 },
      { type: 'SHOP', name: '超市', probability: 0.8 },
    ],
    effect: { mood: 3, energy: 5, social: 0 },
    specialEffect: { type: 'SLEEP_BOOST', value: 5, duration: 0, desc: '睡眠质量+5' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },

  // ======== 特殊/惊喜类 (6个) ========
  {
    itemId: 'box_002', name: '快递盒', type: 'SPECIAL', subType: '惊喜',
    icon: '📦', rarity: 'COMMON',
    description: '双十一快递盒，里面装着未知的惊喜。拆快递的快乐，比买东西本身还快乐。',
    shortDesc: '双十一快递盒',
    price: 0, sellPrice: 0,
    sources: [
      { type: 'EXPLORE', name: '拆快递事件', probability: 1, scene: 'bedroom' },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'RANDOM_ITEM', value: 1, duration: 0, desc: '随机开出1-3个物品' },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'book_011', name: '二手书', type: 'SPECIAL', subType: '书籍',
    icon: '📗', rarity: 'COMMON',
    description: '学长留下的二手书，里面全是笔记和重点标记。这书比新书值钱多了，因为是「开过光」的。',
    shortDesc: '学长二手书',
    price: 10, sellPrice: 5,
    sources: [
      { type: 'EXPLORE', name: '二手群', probability: 0.8, scene: 'town' },
      { type: 'SOCIAL', name: '学长赠送', probability: 0.5 },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 10, duration: 10, desc: '学长笔记加成10分钟' },
    useLimit: { scenes: ['classroom', 'library', 'study_room'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'clothes_001', name: '旧衣服', type: 'SPECIAL', subType: '衣物',
    icon: '👕', rarity: 'COMMON',
    description: '室友不要的旧衣服，说是「没怎么穿」。你穿上发现确实没怎么穿，因为尺码不对。',
    shortDesc: '室友旧衣服',
    price: 0, sellPrice: 0,
    sources: [
      { type: 'SOCIAL', name: '室友赠送', probability: 0.5 },
      { type: 'EXPLORE', name: '二手群', probability: 0.3, scene: 'town' },
    ],
    effect: { mood: 2, energy: 0, social: 0 },
    useLimit: { scenes: ['dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 10,
  },
  {
    itemId: 'equip_001', name: '实验器材', type: 'SPECIAL', subType: '器材',
    icon: '🧪', rarity: 'UNCOMMON',
    description: '实验课发放的器材，烧杯试管量筒。每次实验课都像在做法，只是不知道在召唤什么。',
    shortDesc: '实验课器材',
    price: 0, sellPrice: 5,
    sources: [
      { type: 'TEACHER', name: '实验课发放', probability: 1, scene: 'classroom' },
    ],
    effect: { mood: 3, energy: 0, social: 0 },
    specialEffect: { type: 'STUDY_BOOST', value: 10, duration: 20, desc: '实验加成20分钟' },
    useLimit: { scenes: ['classroom', 'laboratory'], minMood: 0, minEnergy: 0 },
    maxStack: 5,
  },
  {
    itemId: 'badge_001', name: '社团徽章', type: 'SPECIAL', subType: '纪念',
    icon: '🎖️', rarity: 'UNCOMMON',
    description: '社团活动纪念徽章，别在书包上。虽然你去了三次活动就没再去了，但徽章还在。',
    shortDesc: '社团纪念徽章',
    price: 0, sellPrice: 3,
    sources: [
      { type: 'SOCIAL', name: '社团活动', probability: 0.8 },
    ],
    effect: { mood: 5, energy: 0, social: 5 },
    specialEffect: { type: 'IDENTITY_BOOST', value: 1, duration: 0, desc: '身份象征' },
    useLimit: { scenes: ['classroom', 'library', 'dormitory', 'bedroom'], minMood: 0, minEnergy: 0 },
    maxStack: 20,
  },
  {
    itemId: 'cert_001', name: '奖学金证书', type: 'SPECIAL', subType: '荣誉',
    icon: '🏆', rarity: 'LEGENDARY',
    description: '奖学金荣誉证书，全校只有5%的人能获得。爸妈把照片发到家族群，你已经社死了。',
    shortDesc: '奖学金证书',
    price: 0, sellPrice: 0,
    sources: [
      { type: 'SOCIAL', name: '考试事件奖励', probability: 0.2 },
    ],
    effect: { mood: 20, energy: 0, social: 10 },
    specialEffect: { type: 'GLORY_BOOST', value: 10, duration: 0, desc: '炫耀值+10' },
    useLimit: { scenes: ['classroom', 'library', 'dormitory', 'bedroom', 'playground'], minMood: 0, minEnergy: 0 },
    maxStack: 1,
  },
];

ITEM_DATABASE.push(...ITEM_DATABASE_PART4);

// 导出所有数据
module.exports = {
  RARITY,
  ITEM_TYPE,
  ITEM_DATABASE,
};
